export const CHANGE_GAIN = "CHANGE_GAIN";
export const CHANGE_ADSR = "CHANGE_ADSR";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const CHANGE_OSCILLATOR = "CHANGE_OSCILLATOR";
export const CHANGE_OSCILLATOR_VOLUME = "CHANGE_OSCILLATOR_VOLUME";
export const CHANGE_OSCILLATOR_OCTAVE = "CHANGE_OSCILLATOR_OCTAVE";
export const ACTIVATE_NOTE = "ACTIVATE_NOTE";
export const DEACTIVATE_NOTE = "DEACTIVATE_NOTE";
